[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'sh -c "npm run preview -- --host 0.0.0.0 --port \$PORT"'
